# Generated by Django 4.1.7 on 2023-03-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
