# Generated by Django 4.1.7 on 2023-04-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
    ]
